#DEFINE IMPORTANT GLOBALLY ACCESSIBLE GAME ATTRIBUTES
RUNNING = False
DISPLAY_HEIGHT = 600
DISPLAY_WIDTH = (DISPLAY_HEIGHT/3)*4

CANVAS_HEIGHT = 250
CANVAS_WIDTH = (CANVAS_HEIGHT/3)*4

#CANVAS TO DISPLAY SIZE RATIOS
CtoD_w_ratio = CANVAS_WIDTH/DISPLAY_WIDTH
CtoD_h_ratio = CANVAS_HEIGHT/DISPLAY_HEIGHT
#INVERSE RATIOS, DISPLAY TO CANVAS RATIO
DtoC_w_ratio = 1/CtoD_w_ratio
DtoC_h_ratio = 1/CtoD_h_ratio


