#DEFINE IMPORTANT GLOBALLY ACCESSIBLE GAME ATTRIBUTES
RUNNING = False
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600

CANVAS_WIDTH = 282
CANVAS_HEIGHT = (CANVAS_WIDTH/4)*3

CANVAStoDISPLAY_width_ratio = CANVAS_WIDTH/DISPLAY_WIDTH
CANVAStoDISPLAY_height_ratio = CANVAS_HEIGHT/DISPLAY_HEIGHT


